version: "3.9"

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: app
    command: ["/app/app"]

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    command: ["/app/server"]
    ports:
      - "8082:8080"
    restart: always
