services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: stress
    container_name: stress-1
    profiles: ["manual"]

  server:
    build:
      context: .
      dockerfile: Dockerfile
      target: server
    container_name: server-1
    ports:
      - "8082:8080"
    restart: always
