version: "3"

tasks:
  stress:
    desc: "Executa o load tester contra o serviço"
    aliases: ["s"]
    cmds:
      - go run ./cmd/app/main.go run -u {{.URL}} -r {{.REQS}} -c {{.CONC}}
    vars:
      URL: "http://google.com"
      REQS: 100
      CONC: 10
